[package]
name = "mow"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", features = ["persistence"] }
egui = "0.29.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
